#!/bin/bash
ls -a1p --group-directories-first | sed ':a;N;$!ba;s/\n/, /g; s|/\(,\)|/\2|g; s|/\n|/|g' | awk 'BEGIN{a["."]=1; a[".."]=1} {if ($0 in a) print; else b[$0]=1} END{for (i in a) print i; for (j in b) print j}' | sort -k1.2,1n -k1.1,1

